FROM node:6.10.3

# Install ng-cli
RUN npm install -g @angular/cli

# Create a directory where our app will be placed
RUN mkdir -p /app/src

# Change working directory to app directory
WORKDIR /app

# Expose ports
EXPOSE 4200 49153
